### ISSUE TITLE
no padding zeros in interval photo filenames

### ISSUE THREAD

**Issue by yn1v** [futureshocked/bench_computer#1]
In BC_final / bench_computer_v5.py line 502
` self.file_name_interval       = '{}/{}.jpg'.format(self.directory_interval,self.intervalImageCounter)  `

This makes the file names go 2, 3, 4, 5 and so on. When listing names, we end up with 2, 20, 200, 21, 210 and so on. 

Changing this line as follow will add some zero padding to the file name making more easy to create a video time lapse from the photos.

` self.file_name_interval       = '{}/000{}.jpg'.format(self.directory_interval,self.intervalImageCounter)  `

I know it is not pretty, as the length of filename will vary, but listing will be in order nevertheless.

**Comment by futureshocked** [comment]
Hi @yn1v, yes, that's a good idea, I have made the change in the master branch.
